MakeBingo/Models/Board.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace MakeBingo.Models
{
    public class Board
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();

        public string Title { get; set; }
        public string Maker { get; set; }
        public string Link { get; set; }

        [JsonIgnore]
        public string ParentId { get; set; }
        [JsonIgnore]
        public Board Parent { get; set; }

        [JsonIgnore]
        public ICollection<Board> Children { get; set; } = new HashSet<Board>();

        [JsonIgnore]
        public ICollection<Result> Results { get; set; } = new HashSet<Result>();

        private string _cells;

        [NotMapped]
        public BoardCell[][] Cells
        {
            get => JsonConvert.DeserializeObject<BoardCell[][]>(String.IsNullOrWhiteSpace(_cells) ? "[]" : _cells);
            set => _cells = JsonConvert.SerializeObject(value);
        }

        public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.Now;
    }
}

MakeBingo/Models/BoardCell.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MakeBingo.Models
{
    public class BoardCell
    {
        public string Label { get; set; }
        public bool Checked { get; set; }
        public byte Pattern { get; set; }
    }
}

MakeBingo/Models/ErrorViewModel.cs
using System;

namespace MakeBingo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MakeBingo/Models/PostBoardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MakeBingo.Models
{
    public class PostBoardViewModel
    {
        public string Title { get; set; }
        public string Maker { get; set; }
        public string Link { get; set; }
        public string ParentId { get; set; }
        public BoardCell[][] Cells { get; set; }
    }
}

MakeBingo/Models/PostResultViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MakeBingo.Models
{
    public class PostResultViewModel
    {
        public BoardCell[][] Cells { get; set; }
    }
}

MakeBingo/Models/Result.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace MakeBingo.Models
{
    public class Result
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();

        public string BoardId { get; set; }
        public Board Board { get; set; }

        private string _cells;

        [NotMapped]
        public BoardCell[][] Cells
        {
            get => JsonConvert.DeserializeObject<BoardCell[][]>(String.IsNullOrWhiteSpace(_cells) ? "[]" : _cells);
            set => _cells = JsonConvert.SerializeObject(value);
        }

        public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.Now;
    }
}

MakeBingo/Controllers/BoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MakeBingo.Models;
using MakeBingo.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MakeBingo.Controllers
{
    public class BoardController : Controller
    {
        private readonly DatabaseContext _database;

        public BoardController(DatabaseContext database)
        {
            _database = database;
        }

        public IActionResult Create(string parentId = null)
        {
            ViewBag.ParentId = parentId;

            return View();
        }

        public async Task<IActionResult> Play(string id)
        {
            var board = await _database.Boards
                .Include(b => b.Parent)
                .SingleOrDefaultAsync(b => b.Id == id);

            if (board == null)
                return NotFound();

            return View(board);
        }

        public async Task<IActionResult> Detail(string id)
        {
            var board = await _database.Boards
                .Include(b => b.Parent)
                .Include(b => b.Results)
                .SingleOrDefaultAsync(b => b.Id == id);

            if (board == null)
                return NotFound();

            return View(board);
        }

        [Route("api/boards/{id}")]
        public async Task<IActionResult> GetBoard(string id)
        {
            var board = await _database.Boards.FindAsync(id);

            if (board == null)
                return NotFound();

            return Ok(board);
        }

        [HttpPost]
        [Route("api/boards/")]
        public async Task<IActionResult> PostBoard([FromBody] PostBoardViewModel model)
        {
            var board = new Board
            {
                ParentId = model.ParentId,
                Link = model.Link,
                Maker = model.Maker,
                Title = model.Title,
                Cells = model.Cells
            };

            _database.Boards.Add(board);
            await _database.SaveChangesAsync();

            return Ok(new {board.Id});
        }

        [HttpPost]
        [Route("api/boards/{id}/results")]
        public async Task<IActionResult> PostResult(string id, [FromBody] PostResultViewModel model)
        {
            var board = await _database.Boards.FindAsync(id);

            if (board == null)
                return NotFound();

            var result = new Result
            {
                Board = board,
                Cells = model.Cells
            };

            _database.Results.Add(result);
            board.Results.Add(result);

            await _database.SaveChangesAsync();

            return Ok(new {result.Id});
        }
    }
}

MakeBingo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MakeBingo.Models;
using MakeBingo.Services;
using Microsoft.EntityFrameworkCore;

namespace MakeBingo.Controllers
{
    public class HomeController : Controller
    {
        private readonly DatabaseContext _database;

        public HomeController(DatabaseContext database)
        {
            _database = database;
        }

        public async Task<IActionResult> Index()
        {
            var boards = await _database.Boards.Include(b => b.Results).OrderByDescending(b => b.Results.Count).Take(9).ToArrayAsync();

            return View(boards);
        }
    }
}

MakeBingo/Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using MakeBingo.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;

namespace MakeBingo.Controllers
{
    public class ResultController : Controller
    {
        private readonly DatabaseContext _database;
        private readonly CloudBlobClient _blobClient;

        public ResultController(DatabaseContext database, IConfiguration config)
        {
            _database = database;

            var storageAccount = CloudStorageAccount.Parse(config.GetConnectionString("AzureStorage"));
            _blobClient = storageAccount.CreateCloudBlobClient();
        }

        public async Task<IActionResult> Detail(string id)
        {
            var result = await _database.Results
                .Include(r => r.Board)
                    .ThenInclude(b => b.Parent)
                .SingleOrDefaultAsync(r => r.Id == id);

            if (result == null)
                return NotFound();

            return View(result);
        }

        public async Task<IActionResult> Image(string id)
        {
            var result = await _database.Results
                .Include(r => r.Board)
                .ThenInclude(b => b.Parent)
                .SingleOrDefaultAsync(r => r.Id == id);

            if (result == null)
                return NotFound();

            return View(result);
        }

        [Route("api/results/{id}/uploadImage")]
        [HttpPost]
        public async Task<IActionResult> UploadImage(string id, IFormFile image)
        {
            var container = _blobClient.GetContainerReference("images");
            var blob = container.GetBlockBlobReference($"{id}{Path.GetExtension(image.FileName)}");
            blob.Properties.ContentType = image.ContentType;

            await blob.UploadFromStreamAsync(image.OpenReadStream());

            return Created(blob.Uri, null);
        }
    }
}

MakeBingo/Views/Board/Create.cshtml
<div id="create-editor" class="container" style="max-width: 750px;">
    <div class="row mt-5">
        <div class="col-md-3">
            <div class="form-group">
                <label>빙고판 이름</label>
                <input type="text" class="form-control" v-model="title"/>
            </div>
            <div class="form-group">
                <label>빙고판 만든이</label>
                <input type="text" class="form-control" v-model="maker"/>
            </div>
            <div class="form-group">
                <label>만든이 SNS링크</label>
                <input type="text" class="form-control" v-model="link"/>
            </div>
        </div>
    </div>

    <div class="square-wrap mt-3">
        <div class="content">
            <div class="bingo-board">
                <div class="bingo-row" v-for="row in cells">
                    <div class="bingo-cell" v-for="cell in row">
                        <textarea v-model="cell.label" placeholder="항목을 채워주세요"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="text-right mt-3">
        <button class="btn btn-success" @@click="submit">저장</button>
    </div>
</div>

@section Scripts
{
    <script>
        var editor = new Vue({
            el: '#create-editor',
            data: {
                title: '',
                cells: [
                    [{}, {}, {}, {}, {}],
                    [{}, {}, {}, {}, {}],
                    [{}, {}, {}, {}, {}],
                    [{}, {}, {}, {}, {}],
                    [{}, {}, {}, {}, {}]
                ],
                maker: '',
                link: '',
                parentId: null,
            },
            methods: {
                setParent: function (parentId) {
                    var _this = this;
                    window.fetch('/api/boards/' + parentId)
                        .then(function(res) { return res.json(); })
                        .then(function(data) {
                            _this.parentId = parentId;
                            _this.cells = data.cells;
                            _this.title = data.title;
                        });
                },
                submit: function () {
                    var hasBlank = false;

                    for (var i = 0; i < 5; i++) {
                        for (var j = 0; j < 5; j++) {
                            if (!this.cells[i][j].label
                                || this.cells[i][j].label.replace(/\s/g, '').length === 0) {
                                hasBlank = true;
                                break;
                            }
                        }
                        if (hasBlank)
                            break;
                    }

                    if (hasBlank) {
                        alert('모든 항목을 다 채워주세요');
                        return;
                    }

                    window.fetch('/api/boards/',
                            {
                                method: 'POST',
                                body: JSON.stringify({
                                    title: this.title,
                                    cells: this.cells,
                                    maker: this.maker,
                                    link: this.link,
                                    parentId: this.parentId
                                }),
                                headers: {
                                    'Content-Type': 'application/json'
                                }
                            })
                        .then(function(res) { return res.json(); })
                        .then(function(data) {
                            if (data && data.id) {
                                location.href = '/board/detail/' + data.id;
                            } else {
                                alert('저장에 실패했습니다');
                            }
                        });
                }
            },
            mounted: function () {
            }
        })
    </script>
    
    @if (ViewBag.ParentId != null)
    {
        <script>
            editor.setParent('@ViewBag.ParentId');
        </script>
    }
}

MakeBingo/Views/Board/Detail.cshtml
@model Board
@section Headers {
    <meta property="og:title" content="@Model.Title - 나만의 빙고" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://bingo.variel.kr/board/detail/@Model.Id" />
}
<div class="container" style="max-width: 750px;">
    <h2 class="text-center mt-5">@Model.Title</h2>
    <p class="text-right mb-0">
        @if (!String.IsNullOrWhiteSpace(Model.Maker))
        {
            if (!String.IsNullOrWhiteSpace(Model.Link))
            {
                <text>만든이 : <a href="@Model.Link" target="_blank">@Model.Maker</a></text>
            }
            else
            {
                <text>만든이 : @Model.Maker</text>
            }
        }
    </p>
    <p class="text-right">
        @if (Model.Parent != null)
        {
            <text>원본 : <a href="@Url.Action("Detail", "Board", new {id = Model.ParentId})">@Model.Parent.Title - @Model.Parent.Maker</a></text>
        }
    </p>

    <div class="square-wrap mt-3">
        <div class="content">
            <div class="bingo-board">
                @foreach (var row in Model.Cells)
                {
                    <div class="bingo-row">
                        @foreach (var cell in row)
                        {
                            <div class="bingo-cell">
                                @cell.Label
                            </div>
                        }
                    </div>
                }
            </div>
        </div>
    </div>

    <div class="text-center mt-5">
        <a href="@Url.Action("Play", "Board", new {id = Model.Id})" class="btn btn-primary btn-lg text-white px-5 py-3"><i class="fa fa-play"></i> 빙고 시작</a>
    </div>
    <div class="text-center mt-3">
        <a href="@Url.Action("Create", "Board", new {parentId = Model.Id})" class="btn btn-secondary"><i class="fa fa-copy"></i> 빙고판 복제</a>
    </div>
</div>

MakeBingo/Views/Board/Play.cshtml
@model Board
<div id="bingo" class="container" style="max-width: 750px;">
    <h2 class="text-center mt-5">@Model.Title</h2>
    <p class="text-right mb-0">
        @if (!String.IsNullOrWhiteSpace(Model.Maker))
        {
            if (!String.IsNullOrWhiteSpace(Model.Link))
            {
                <text>만든이 : <a href="@Model.Link" target="_blank">@Model.Maker</a></text>
            }
            else
            {
                <text>만든이 : @Model.Maker</text>
            }
        }
    </p>
    <p class="text-right">
        @if (Model.Parent != null)
        {
            <text>원본 : <a href="@Url.Action("Detail", "Board", new {id = Model.ParentId})">@Model.Parent.Title - @Model.Parent.Maker</a></text>
        }
    </p>

    <div class="square-wrap mt-3">
        <div class="content">
            <div class="bingo-board">
                <div class="bingo-row" v-for="row in cells">
                    <div class="bingo-cell" v-for="cell in row" @@click="cell.checked = !cell.checked; cell.pattern = Math.floor(Math.random() * 6 + 1);">
                        <div class="bingo-overlay" v-show="cell.checked" v-bind:class="[ 'crayon' + cell.pattern ]"></div>
                        {{ cell.label }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="text-center my-5">
        <button class="btn btn-primary btn-lg text-white px-5 py-3" @@click="save"><i class="fa fa-save"></i> 저장</button>
        <a href="@Url.Action("Play", "Board", new {id = Model.Id})" class="btn btn-secondary btn-lg text-white px-4 py-3"><i class="fa fa-share"></i> 빙고판 공유</a>
    </div>
</div>

@section Scripts{ 
    <script>
        var bingo = new Vue({
            el: '#bingo',
            data: {
                cells: [
                    [{}, {}, {}, {}, {}],
                    [{}, {}, {}, {}, {}],
                    [{}, {}, {}, {}, {}],
                    [{}, {}, {}, {}, {}],
                    [{}, {}, {}, {}, {}]
                ],
                boardId: '@Html.Raw(Model.Id)'
            },
            methods: {
                save: function() {
                    fetch('/api/boards/' + this.boardId + '/results',
                            {
                                method: 'POST',
                                headers: {
                                    'Content-Type': 'application/json'
                                },
                                body: JSON.stringify({
                                    cells: this.cells
                                })
                            })
                        .then(function(res) { return res.json() })
                        .then(function(data) {
                            if (data && data.id) {
                                location.href = '/result/image/' + data.id;
                            } else {
                                alert('저장 중 오류가 발생했습니다');
                            }
                        });
                }
            },
            mounted: function() {
                var _this = this;
                window.fetch('/api/boards/' + this.boardId)
                    .then(function(res) { return res.json(); })
                    .then(function(data) {
                        _this.cells = data.cells;
                    });
            }
        });
    </script>
}

MakeBingo/Views/Home/Index.cshtml
@model Board[]
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="text-center my-5">
        <h1>나만의 빙고</h1>
        <h3>이미 만들어진 빙고를 플레이 해보세요</h3>
    </div>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-4">
                <div class="card my-2">
                    <div class="card-body">
                        <h5 class="card-title">@item.Title</h5>
                        <h6 class="card-subtitle text-muted mb-2">@(String.IsNullOrWhiteSpace(item.Maker) ? "이름없음" : item.Maker)</h6>
                        <p class="card-text">@(item.Results.Count)명이 이용</p>
                        <a href="@Url.Action("Detail", "Board", new {item.Id})">빙고 하기 <i class="fa fa-angle-right"></i></a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

MakeBingo/Views/Result/Detail.cshtml
@model Result
@section Headers {
    <meta property="og:title" content="@Model.Board.Title - 나만의 빙고"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="https://bingo.variel.kr/result/detail/@Model.Id"/>
    <meta property="og:image" content="https://mybingo.blob.core.windows.net/images/@(Model.Id).png"/>
}
<div id="bingo" class="container" style="max-width: 750px;">
    <h2 class="text-center mt-5">
        <a href="@Url.Action("Detail", "Board", new {Model.Board.Id})">@Model.Board.Title</a>
    </h2>
    <p class="text-right mb-0">
        @if (!String.IsNullOrWhiteSpace(Model.Board.Maker))
        {
            if (!String.IsNullOrWhiteSpace(Model.Board.Link))
            {
                <text>만든이 : <a href="@Model.Board.Link" target="_blank">@Model.Board.Maker</a></text>
            }
            else
            {
                <text>만든이 : @Model.Board.Maker</text>
            }
        }
    </p>
    <p class="text-right">
        @if (Model.Board.Parent != null)
        {
            <text>원본 : <a href="@Url.Action("Detail", "Board", new {id = Model.Board.ParentId})">@Model.Board.Parent.Title - @Model.Board.Parent.Maker</a></text>
        }
    </p>

    <div class="square-wrap mt-3">
        <div class="content">
            <div class="bingo-board">
                @foreach (var row in Model.Cells)
                {
                    <div class="bingo-row">
                        @foreach (var cell in row)
                        {
                            <div class="bingo-cell">
                                @if (cell.Checked)
                                {
                                    <div class="bingo-overlay crayon@(cell.Pattern)"></div>
                                }
                                @cell.Label
                            </div>
                        }
                    </div>
                }
            </div>
        </div>
    </div>

    <div class="text-center my-5">
        <div class="dropdown d-inline-block my-2">
            <button class="btn btn-lg btn-primary px-5 py-3 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-share"></i> 결과 공유
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https://bingo.variel.kr/result/detail/@(Model.Id)"><i class="fab fa-facebook mr-1"></i> 페이스북</a>
                <a class="dropdown-item" target="_blank" href="https://twitter.com/share?text=@Html.UrlEncoder.Encode(Model.Board.Title)&url=https://bingo.variel.kr/result/detail/@(Model.Id)"><i class="fab fa-twitter mr-1"></i> 트위터</a>
            </div>
        </div>
        <a href="@Url.Action("Detail", "Board", new {Model.Board.Id})" class="btn btn-success btn-lg text-white px-5 py-3 my-2"><i class="fa fa-play"></i> 다시 하기</a>
        <a href="https://mybingo.blob.core.windows.net/images/@(Model.Id).png" class="btn btn-secondary btn-lg text-white px-3 py-3 my-2" target="_blank"><i class="fa fa-download"></i> 이미지 다운로드</a>
    </div>
</div>
@section Scripts {
    <script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>
    <script></script>
}

MakeBingo/Views/Result/Image.cshtml
@model Result
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=1280;" />
    <title>빙고 만들기</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
          crossorigin="anonymous"
          integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="min-width: 1280px;">
    <div id="bingo" class="p-3" style="width: 1280px;">
        <h2 class="text-center mt-2">
            @Model.Board.Title
        </h2>
        <div style="max-width: 720px;" class="mx-auto">
            <p class="text-right mb-0">
                @if (!String.IsNullOrWhiteSpace(Model.Board.Maker))
                {
                    if (!String.IsNullOrWhiteSpace(Model.Board.Link))
                    {
                        <text>만든이 : @Model.Board.Maker</text>
                    }
                    else
                    {
                        <text>만든이 : @Model.Board.Maker</text>
                    }
                }
            </p>
            <p class="text-right">
                @if (Model.Board.Parent != null)
                {
                    <text>원본 : <a href="@Url.Action("Detail", "Board", new {id = Model.Board.ParentId})">@Model.Board.Parent.Title - @Model.Board.Parent.Maker</a></text>
                }
            </p>
        </div>
        <div class="square-wrap mt-3">
            <div class="content">
                <div class="bingo-board">
                    @foreach (var row in Model.Cells)
                    {
                        <div class="bingo-row">
                            @foreach (var cell in row)
                            {
                                <div class="bingo-cell">
                                    @if (cell.Checked)
                                    {
                                        <div class="bingo-overlay crayon@(cell.Pattern)"></div>
                                    }
                                    @cell.Label
                                </div>
                            }
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <script src="https://unpkg.com/promise-polyfill"></script>
    <script src="https://unpkg.com/whatwg-fetch"></script>
    <script src="https://unpkg.com/vue"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"
            integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
    </script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>
    <script>
        function dataURItoBlob(dataURI) {
            // convert base64/URLEncoded data component to raw binary data held in a string
            var byteString;
            if (dataURI.split(',')[0].indexOf('base64') >= 0)
                byteString = atob(dataURI.split(',')[1]);
            else
                byteString = unescape(dataURI.split(',')[1]);
            // 마임타입 추출
            var mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
            // write the bytes of the string to a typed array
            var ia = new Uint8Array(byteString.length);
            for (var i = 0; i < byteString.length; i++) {
                ia[i] = byteString.charCodeAt(i);
            }
            return new Blob([ia], {type:mimeString});
        }

        var bingo = document.querySelector('#bingo');
        html2canvas(bingo)
            .then(canvas => {
                bingo.remove();

                var form = new FormData();
                form.append("image", dataURItoBlob(canvas.toDataURL('image/png')), 'file.png');

                fetch('/api/results/@(Model.Id)/uploadImage',
                        {
                            method: 'POST',
                            body: form
                        })
                    .then(function(res) {})
                    .then(function (data) {
                        location.href = '@Url.Action("Detail", new {Model.Id})';
                    });
            });
    </script>
</body>
</html>

MakeBingo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @RenderSection("Headers", false)
    <title>나만의 빙고</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
          crossorigin="anonymous"
          integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="/">나만의 빙고</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="@Url.Action("Create", "Board")">빙고판 만들기</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Variel Creatives
        </div>
    </footer>
    <script src="https://unpkg.com/promise-polyfill"></script>
    <script src="https://unpkg.com/whatwg-fetch"></script>
    <script src="https://unpkg.com/vue"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"
            integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
    </script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>